# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference

# For a detailed guide to building and testing with Node, read the docs:
# https://circleci.com/docs/language-javascript/ for more details
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  # See the Node orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.2
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          account_id: "471112554816"
          auth:
            - aws-cli/setup:
                aws_access_key_id: echo ${AWS_ACCESS_KEY}
                aws_secret_access_key: echo ${AWS_SECRET_ACCESS_KEY}
                region: us-east-2
          context: CircleCI_OIDC_Token
          create_repo: true
          dockerfile: Dockerfile
          extra_build_args: '--compress'
          no_output_timeout: 20m
          path: docker
          platform: linux/amd64
          profile_name: OIDC-User
          public_registry: false
          push_image: true
          region: us-east-2
          repo: smartinvest-ui


